#!/usr/bin/env bash
# Copies real Measure files of this repository into real.ts as string constants.
# The test environment has no file access, so the fixtures are TypeScript modules.
# Run it again only when a test needs newer real data.
set -euo pipefail
here=$(cd "$(dirname "$0")" && pwd)
repo=$(cd "$here/../../../.." && pwd)
m="$repo/measure"
str() { jq -Rs . < "$1"; }
{
  echo "// Generated by sync-real.sh from this repository's measure/ folder. Do not edit."
  echo "// Snapshot of commit $(git -C "$repo" rev-parse --short=7 HEAD)."
  echo
  printf 'export const INDEX = %s\n\n' "$(str "$m/index.md")"
  printf 'export const TRACKS = %s\n\n' "$(str "$m/tracks.md")"
  printf 'export const BENCHMARK_PLAN = %s\n\n' "$(str "$m/tracks/agent_performance_benchmarking_20260527/plan.md")"
  printf 'export const GUARD_PLAN = %s\n' "$(str "$m/tracks/measure_guard_20261004/plan.md")"
} > "$here/real.ts"
echo "wrote $here/real.ts"
